/*          ### QUESTION###
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include <stdio.h>
#include <stdlib.h>

int main(){
    int i,sum = 0;
    for(i = 3; i<1000; i++){
        if(i%3 == 0 || i%5 == 0)
            sum += i;
    }
    printf("%d", sum);
    return 0;
}
